spring:
  application:
    name: order

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        orderIn-in-0:
          destination: order-exchange
          group: ${spring.application.name}