spring:
  application:
    name: order

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: order

  jpa:
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        orderIn-in-0:
          destination: order-exchange
          group: ${spring.application.name}
        orderOut-out-0:
          destination: order-processed-exchange
          group: ${spring.application.name}
      rabbit:
        bindings:
          orderOut-out-0:
            producer:
              declare-exchange: true
              exchange-type: topic